# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 06:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=50, verbose_name='番剧名')),
                ('anime_intro', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='番剧简介')),
                ('n_point', models.IntegerField(blank=True, null=True, verbose_name='点击量')),
                ('n_collection', models.IntegerField(blank=True, null=True, verbose_name='收藏量')),
                ('website', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=512, null=True, verbose_name='播放网站')),
                ('anime_image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='anime_pic/', verbose_name='番剧图片')),
                ('anime_image_small', easy_thumbnails.fields.ThumbnailerImageField(upload_to='anime_pic/', verbose_name='番剧小图')),
                ('episode_num', models.IntegerField(verbose_name='番剧集数')),
            ],
            options={
                'verbose_name': '番剧',
                'verbose_name_plural': '番剧',
                'ordering': ['n_point'],
            },
        ),
        migrations.CreateModel(
            name='AnimeTimeWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.CharField(max_length=10, verbose_name='每周播放时间')),
            ],
            options={
                'verbose_name': '每周播放时间',
                'verbose_name_plural': '每周播放时间',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=50, verbose_name='角色名')),
                ('character_image', easy_thumbnails.fields.ThumbnailerImageField(max_length=50, upload_to='character_pic', verbose_name='角色图片路径')),
                ('character_intro', ckeditor_uploader.fields.RichTextUploadingField(max_length=512, verbose_name='角色介绍')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.AnimeList', verbose_name='番剧名')),
            ],
            options={
                'verbose_name': '主要角色',
                'verbose_name_plural': '主要角色',
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician_name', models.CharField(max_length=512, verbose_name='音乐')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=50, verbose_name='公司名')),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
            },
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervision_name', models.CharField(max_length=50, verbose_name='监督名')),
            ],
            options={
                'verbose_name': '监督',
                'verbose_name_plural': '监督',
            },
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_actor_name', models.CharField(max_length=50, verbose_name='声优名')),
            ],
            options={
                'verbose_name': '声优',
                'verbose_name_plural': '声优',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='voice_actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.VoiceActor', verbose_name='配音的声优'),
        ),
        migrations.AddField(
            model_name='animelist',
            name='anime_time_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.AnimeTimeWeek', verbose_name='每周播放时间'),
        ),
        migrations.AddField(
            model_name='animelist',
            name='musician',
            field=models.ManyToManyField(to='anime.Musician', verbose_name='音乐'),
        ),
        migrations.AddField(
            model_name='animelist',
            name='release_date',
            field=models.ManyToManyField(to='tags.ReleaseDate', verbose_name='番剧日期'),
        ),
        migrations.AddField(
            model_name='animelist',
            name='staff',
            field=models.ManyToManyField(to='anime.Staff', verbose_name='制作公司'),
        ),
        migrations.AddField(
            model_name='animelist',
            name='supervision',
            field=models.ManyToManyField(to='anime.Supervision', verbose_name='监督名'),
        ),
        migrations.AddField(
            model_name='animelist',
            name='tags',
            field=models.ManyToManyField(to='tags.Tags', verbose_name='标签'),
        ),
    ]
