# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animelist',
            name='n_collection',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏量'),
        ),
        migrations.AlterField(
            model_name='animelist',
            name='n_point',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='点击量'),
        ),
    ]
